name: madboxes
description: A 2 player game based on 3 colouring problem

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  google_sign_in: ^5.0.0
  googleapis: ^2.0.0
  googleapis_auth: ^1.1.0
  uuid: 3.0.3
  animated_text_kit: ^4.0.0
  provider: ^5.0.0
  rive: ^0.7.1
  font_awesome_flutter: ^9.0.0
  flutter_form_builder:
  flutter_riverpod:
  shared_preferences: ^2.0.5
  google_fonts:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
       - assets/google_logo.png
       - assets/bgtop.jpeg
       - assets/marty_v6.riv
       - assets/default_profile.png
       - assets/event_pages.riv
       - assets/event_pages2.riv
       - assets/knight063.riv
       - assets/iron_giant2.riv
       - assets/buggy.riv
       - assets/phone_drop.riv

